In [14]:
import json
import random
import time
import math
from ast import literal_eval as make_tuple
import numpy as np
import pandas as pd
# import psutil
from utils import mnist_reader
import pdb
import matplotlib.pyplot as plt
%matplotlib inline

In [15]:
from sklearn.decomposition import PCA
from sklearn.svm import LinearSVC 
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression as Linear

In [21]:
DATA_DIR='data/fashion/'
train, y_train = mnist_reader.load_mnist(path=DATA_DIR, kind='train')
test, y_test = mnist_reader.load_mnist(path=DATA_DIR, kind='t10k')

# from sklearn.decomposition import PCA
print(train.shape)
pca=PCA(n_components=40)
train=pca.fit_transform(train)
print(train.shape)
test=pca.transform(test)

(60000, 784)
(60000, 40)


In [26]:
# clf = SVR('linear')
clf=LinearSVC(C=0.01)
clf.fit(train,y_train)
preds_tr=clf.predict(train)
preds=clf.predict(test)

In [27]:
print(preds_tr,y_train)

[9 0 3 ... 3 3 5] [9 0 0 ... 3 0 5]


In [28]:
print(preds,y_test)

[9 2 1 ... 3 1 5] [9 2 1 ... 8 1 5]


In [29]:
acc_tr=np.sum(y_train==preds_tr)/y_train.shape
acc=np.sum(y_test==preds)/y_test.shape
print(acc,acc_tr)
print(results.scores(y_test,preds))

[0.6779] [0.68365]
(0.7262296483959062, 0.6779, 0.6644355218344558)


In [16]:
data = pd.read_csv('railwayBookingList.csv')

print(data.head())


dict_class={'FIRST_AC':0,'SECOND_AC':1,'THIRD_AC':2,'NO_PREF':3}
for i in range(data.shape[0]):
    data['preferredClass'][i]=dict_class[data['preferredClass'][i]]
    

data['sex'][(data['sex']=='male')]=0
data['sex'][(data['sex']=='female')]=1

sorted_b=np.sort(np.array(data['budget'].unique()))
for x,i in enumerate(sorted_b):
        data['budget'][data['budget']==i]=x

data.head()

y=data['boarded']
X = data.as_matrix()
X=X[:-1,2:]
y=y[:-1]
y=np.array(y)
print(X.shape)

from sklearn.model_selection import StratifiedShuffleSplit
sss = StratifiedShuffleSplit(n_splits=1, test_size=0.2)
sss.get_n_splits(X, y)
for train_index, test_index in sss.split(X, y):
    train, y_train = X[train_index], y[train_index]
    test, y_test = X[test_index], y[test_index]

y_train=np.array(y_train)
train=np.array(train)
test=np.array(test)
y_test=np.array(y_test)


       caseID  boarded  budget  memberCount preferredClass     sex  age
0   111131089        0    2201            0       FIRST_AC  female    2
1  2489059216        0    1775            3       FIRST_AC    male    0
2  1565109576        1    1775            3       FIRST_AC  female    0
3  1373075087        1    1775            3       FIRST_AC    male    3
4  1598041082        1    1775            3       FIRST_AC  female    2


/home/khushal/anaconda3/envs/deeplearning/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/home/khushal/anaconda3/envs/deeplearning/lib/python3.6/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
/home/khushal/anaconda3/envs/deeplearning/lib/python3.6/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.p

(1309, 5)


In [19]:
data = pd.read_csv('Assignment2Data_4.csv')

print(data.head())

data.head()

X=np.array(data['x'])
y=np.array(data['levels'])
X=np.vstack((X,X**2,X**3,X**4)).T

print(X.shape)

print(y.shape)

from sklearn.cross_validation import train_test_split

tr_idx=np.random.randint(0,X.shape[0],(int)(.8*X.shape[0]))
train,test,y_train,y_test=train_test_split(X, y, test_size=0.2,random_state=0)


           x     levels
0  37.552555  24.580169
1  81.145268  19.187001
2   0.273643  50.161268
3  43.310435  26.110681
4  67.253264  26.746186
(10000, 4)
(10000,)


/home/khushal/anaconda3/envs/deeplearning/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [5]:
data = pd.read_csv('Medical_data.csv')
X = data.as_matrix()
print(X)
y=np.empty(X.shape[0])
for i in range(X.shape[0]):
    if(X[i,0]=='HEALTHY'):
        y[i]=0
    if(X[i,0]=='SURGERY'):
        y[i]=1
    if(X[i,0]=='MEDICATION'):
        y[i]=2
print(y.shape)
X = X[:,1:4]
y=np.array(y,dtype='int')

[['HEALTHY' 1.6315155608144196 -0.26444658130172355 2.534567146651425]
 ['SURGERY' 0.15395105426389907 1.419533481505174 1.3331207912724836]
 ['HEALTHY' 2.021729118164318 0.26204637889999405 2.8799717380508727]
 ...
 ['HEALTHY' 0.19320188275265227 0.36039894430698144 1.8676445668171464]
 ['HEALTHY' 1.6840959730399991 -0.02321819895892971 3.306257682435044]
 ['MEDICATION' 0.9752179047232428 2.305958926888452 0.22982688347681815]]
(3000,)


In [3]:
data_test = pd.read_csv('test_medical.csv')
X_test = data_test.as_matrix()
# print(X)
y_test=np.empty(X_test.shape[0])
for i in range(X_test.shape[0]):
    if(X_test[i,0]=='HEALTHY'):
        y_test[i]=0
    if(X_test[i,0]=='SURGERY'):
        y_test[i]=1
    if(X_test[i,0]=='MEDICATION'):
        y_test[i]=2
print(y_test.shape)  
X_test = X_test[:,1:4]
y_test=np.array(y_test,dtype='int')

(3000,)


In [6]:
train=X
y_train=y
test=X_test
print(y_train)

[0 1 0 ... 0 0 2]


In [7]:
print(train.shape,y_train.shape)

(3000, 3) (3000,)


In [12]:
from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve
from scipy import interp
class metrics:
    def accuracy(self,y,preds):
        return np.sum(y==preds)/y.shape[0]
    
    def scores(self,y_true,y_pred):
        tp =(y_true == y_pred)
        tp_sum=np.bincount(y_true[tp].astype(int))
        pred_sum=np.bincount(y_pred.astype(int))
        true_sum=np.bincount(y_true.astype(int))
        precision = tp_sum/pred_sum
        recall = tp_sum/true_sum
        f_score = ((2) * precision * recall /
                   (precision + recall))
        precision = np.average(precision)
        recall = np.average(recall)
        f_score = np.average(f_score)

        return precision, recall, f_score
    
    def binary_roc_curve(self,y,probs,*args,**kwargs):
        y = (y == 1)

        desc_score_indices = np.argsort(probs)[::-1]
        probs = probs[desc_score_indices]
        y = y[desc_score_indices]
        distinct_value_indices = np.where(np.diff(probs))[0]
        threshold_idxs = np.r_[distinct_value_indices, y.size - 1]

        tps = y[threshold_idxs]
        fps = 1 + threshold_idxs - tps
        thresholds=y[threshold_idxs]
        optimal_idxs = np.where(np.r_[True,np.logical_or(np.diff(fps, 2),np.diff(tps, 2)),True])[0]
        fps = fps[optimal_idxs]
        tps = tps[optimal_idxs]
        thresholds = thresholds[optimal_idxs]
        print(fps,tps)
        fpr = fps / fps[-1]
        tpr = tps / tps[-1]

        return fpr, tpr, thresholds    
        
    def multiclass_roc_curve(self,y,y_score,ax,label,*args,**kwargs):
        n_classes=y.max()+1
#         print(n_classes)
        if(n_classes==2):
            y_test = np.array([1-y,y]).T
            print(y_test.shape)
        else:
            y_test = label_binarize(y, classes=np.arange(n_classes))
#         print(y_test)
        fpr = dict()
        thresholds=dict()
        tpr = dict()
        roc_auc = dict()
#         print(y_test.shape,y_score.shape)
        for i in range(n_classes):
            fpr[i], tpr[i], _ = roc_curve(y_test[:, i], y_score[:, i])
        all_fpr = np.unique(np.concatenate([fpr[i] for i in range(n_classes)]))
        mean_tpr = np.zeros_like(all_fpr)
        for i in range(n_classes):
            mean_tpr += interp(all_fpr, fpr[i], tpr[i])
        mean_tpr /= n_classes
        fpr["macro"] = all_fpr
        tpr["macro"] = mean_tpr
        ax.plot(fpr["macro"], tpr["macro"],label=label, linestyle=':', linewidth=4)


results=metrics()